### PR TITLE
Fixing issue #43 and removed zero char in matuc help

### PR DESCRIPTION
**Pull request by xplhak**

### CODE REVIEW

**Comment by humenda** [comment]
Thanks for the PR.

Please use 'page' only in lower case in MAGSBS.config (starting from line 320).
This needs to be corrected in MAGSBS.config . A quick `grep -r Page` didn't
reveal any usage of "Page" as translation string (correct me if I'm wrong).
However, your PR introduces these, so please revert.

Please try to minimise spacing changes; in MAGSBS.mparser.__init__:149, you have
inserted a IMHO useless space after the hash. Thanks.

A few lines afterwards, you  capitalised
"raise errors.FormattingError("Cannot recognize page number","
This is wrong. I am aware that I might have done that a few times as well, but
python exceptions should IMHO start lower case, since the messages are usually
printed after a colon, have a look at the documentation here:
<https://docs.python.org/3/tutorial/errors.html>. I would appreciate if you
rather correct exception strings to start lower case.

MAGSBS.pagenumbering:36
Please undo the indentation change. I mostly followed the convention that blocks
have four spaces, continued lines are 8 spaces. I personnally do not want a line
to start at the end of the screen. Please frefrain from this kind of changes, it
only adds noise to the diff. We could discuss using a code reformatter, but
manual reindenting leads to a spacing war :).
I see quite a lot of spacing problems while reading the diff. Please go through
the diff and undo those or comment here to explain. I find multiple blocks in
the diff without a real change, because you added spaces after or before a
comment hash.

I know that this is very picky, but we're discussing on a high level. I would
appreciate if you would correct the points and push again.
Thanks

**Comment by xplhak** [comment]
Hi,

"A quick `grep -r Page` didn't reveal any usage of "Page" as translation string (correct me if I'm wrong). However, your PR introduces these, so please revert."

This translation string is used in pagenumbering.py, line 49 because we need to insert the "|| - Page 1 -" with capitalized P. Otherwise, for English, the translation string is used. We can solve this issue directly within pagenumbering.py (call method like upper_first that can be implementented in Translate class  - or if you have another solution, please suggest it).

I understand your following points, I used PyCharm to refactor the code (to follow <https://pypi.python.org/pypi/pycodestyle>), but it is not really neccessary and I understand that it involves useless changes (like this additional spaces).

I am going to correct only typos.

**Comment by humenda** [comment]
It seems as there has been a misunderstanding. I really do not want "page" to be
capitalised. Nouns are not capitalised by default and "- page xyz -" is not a
heading. Therefore I would argue that "page" should be lowercase. See also
<https://english.stackexchange.com/questions/1367/page-2-or-page-2>. Therefore I
currently think #43 is not really a bug. What do you think?

PyCharm: ok, sounds  useful. But if we go down this route, we really should
discuss before on whether we take the supplied style and we should change all
files at once in one commit and in a separate PR / I could do it as well.

**Comment by xplhak** [comment]
OK, looks like the matter of design, I changed it because Jens requested it. Maybe it should be better to discuss this with him next week when he returns from vacation.
 
Good point about changing style, we can discuss it as well.

**Pull request closed without merging**
