### PR TITLE
Added black config and reformatted code base

### PR DESCRIPTION
**Pull request by efficiosoft**
The Python code is now formatted using the black code formatter. An
appropriate section has been added to README.md to ask contributors to
run black before committing. Black is configured in pyproject.toml.

### CODE REVIEW

**Comment by humenda** [comment]
Thanks for this PR! I actually like the restyling. However, for "Git blame" to
tell the "truth" I think it might be better if I apply the changes.
If you don't mind this, I've pushed an altered version to the branch use_black
with your commit stripped to adding the README section and the configuration
and my commit on top that reformats the repository. What do you think? If you
are fine, I'll merge + close this PR.

**Comment by efficiosoft** [comment]
I'm fine with anything that keeps conveying the purpose of the unifying initiative. Nice git plumbing BTW.

However, I think the line length of just 80 characters is not optimal. While of course magical 80 is the width of ancient terminals, black's default of 88 feels more appropriate on today's larger screens. It also shortens code significantly (~-500 lines) because ~80 seems to be a kind of sweet spot of common line lengths. Anyway, I'm fine with 80, too, if you really prefer that.

I checked out your use_black branch and ran black (v19.10b0) on it, and it still found something to reformat, so you'll probably need to redo your commit once more.

**Comment by humenda** [comment]
>However, I think the line length of just 80 characters is not optimal. While
>of course magical 80 is the width of ancient terminals,

For the sake of completeness, it is also the width of braille displays used
for office purposes, any larger one would be impractical. 88 characters is not
related to the screen width, since  commonscreen setups allow more than 200
characters per line, so this is not really an argument ;-). Limiting the
screen size is helpful for a vertical screen split, though 80 vs. 88 doesn't
really make a difference.
It's all preference, you certainly know PEP 8
<https://www.python.org/dev/peps/pep-0008>.

Thanks for the hint about reformatting, I'll install the latest black and
think about the line length ;).

**Comment by efficiosoft** [comment]
> For the sake of completeness, it is also the width of braille displays used
for office purposes, any larger one would be impractical.

That's a valid point on its own. So if it helps you any, take the chance and leave it at 80.

> Limiting the
screen size is helpful for a vertical screen split, though 80 vs. 88 doesn't
really make a difference.

Not in that regard, right. But as I said, it notably shortens code since line lengths of around 80ish seem to be quite common (no references on it though).

But fair enough, the point about braille displays seems to be an unquestionable argument to me, especially in the context of this particular project, so I'm ok with it.

**Comment by humenda** [comment]
Thanks has been merged.

**Pull request closed without merging**
